### ISSUE TITLE
Moving Use-it-or-lose-it forward?

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/edm#2]
The IAB had previously started work on this document:

https://tools.ietf.org/html/draft-iab-use-it-or-lose-it
https://github.com/intarchboard/use-it-or-lose-it

This certainly seems in scope for discussing evolvability.

**Comment by mirjak** [comment]
There is also https://datatracker.ietf.org/doc/draft-iab-protocol-maintenance/ which is probably related. Maybe these two point could be put together into one bigger doc. Or maybe it just right to have this split, one focusing on evolvability and the other on maintenance. However, maybe there are more things we want to say on both points?

**Comment by tfpauly** [comment]
Replacing this with #12 , now that we did address use-it-or-lose-it.
